_BASE_: "diffusion.yaml"

####################################### DATASETS #######################################
DATASETS:
  TRAIN: 'MSCoCoDiffusionKDDataset'

###################################### DATALOADER ######################################
DATALOADER:
  TRAIN_BATCH_SIZE: 32
  SEQ_PER_SAMPLE: 5

  KD_PRED_FILE: "E:/datasets/COCO/feature/mscoco/data/autoregressive_teacher_pred_ep25.pkl"
  USE_KD_TOKENS_AS_INPUT: True

######################################### Engine #########################################
ENGINE:
  NAME: 'RLDiffusionTrainer'

######################################### MODEL #########################################
MODEL:
  WEIGHTS: './output/stage1/xe/1.1916_Epoch_00049_Iter_0173459.pth'

####################################### Optimizer #######################################

SOLVER:
  NAME: 'Adam'
  EPOCH: 60
  BASE_LR: 0.00001

####################################### lr scheduler ####################################### 
LR_SCHEDULER:
  NAME: 'FixLR'

####################################### losses ####################################### 
LOSSES:
  NAMES: []